Repository pulumi/pulumi-google-native, pull requests merged in 2022-03, with the labels that each got.

#363 Minor cleanup in http handler
  provider/pkg/googleclient/http.go
Labels: impact/no-changelog-required

#383 Drop obsolete substitution logic from provider Update
  provider/pkg/provider/provider.go
Labels: impact/no-changelog-required

#398 Add retryable transport logic
  provider/go.mod
  provider/go.sum
  provider/pkg/googleclient/error_retry_predicates.go
  provider/pkg/googleclient/http.go
  provider/pkg/googleclient/retry_transport.go
Labels: impact/no-changelog-required, automation/merge

#406 [internal] Change GHA to use setup-gcloud@v0
  .github/workflows/master.yml
  .github/workflows/prerelease.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: impact/no-changelog-required

#424 Add tag_sdk step to release GHA spec
  .github/workflows/release.yml
Labels: impact/no-changelog-required, kind/engineering
